###############################################################
#   ModelSim Synthesis script                                 #
# It synthesizes the IP's VHDL files generated by the HLS for #
# RTL simulation with ModelSim.                               #
# It will create the 'work' folder for the simulation files.  #
###############################################################
vlib work
vcom -quiet ../../VLSIProject/solution1/syn/vhdl/*.vhd
#vcom -quiet ./vhdl/*.vhd
